---
title: "Análise de cluster"
author: "Curso-R"
date: "28 de junho de 2018"
output: 
  html_document:
    self_contained: no
---

# Dados

```{r}
library(tidyverse)
library(recipes)

df_food <- read_csv('http://www.biz.uiowa.edu/faculty/jledolter/DataMining/protein.csv')

df_food
```

```{r}
rec_food <- recipe(df_food) %>%
  step_center(all_numeric()) %>%
  step_scale(all_numeric()) 
rec_food

prep_food <- prep(rec_food, training = df_food,verbose = TRUE)

food <- bake(prep_food, newdata = df_food)
```


# K-means: carne vermelha vs carne branca

```{r}
set.seed(29062018)

kmean_fit <- kmeans(
  food[,c("WhiteMeat","RedMeat")], 
  centers = 3,
  nstart = 10
)

kmean_fit
```

# Grupos

```{r}
food %>% 
  mutate(grupo = kmean_fit$cluster) %>% 
  arrange(grupo) %>% 
  select(Country, grupo)
```

# Gráficos

```{r}
food %>% 
  mutate(grupo = as.factor(kmean_fit$cluster)) %>% 
  ggplot(
    aes(x = RedMeat, y = WhiteMeat, label = Country, color = grupo)
  ) +
  geom_text()
```

# Exercício

1) Teste com diferentes valores de `centers` e `nstart` e veja se há interpretações interessantes.

2) Refaça a análise para avaliar Carne vermelha vs Peixe



# Usando todas as variáveis

```{r}
kmean_fit <- kmeans(
  food[, -1], 
  centers = 3, 
  nstart = 10
)

kmean_fit

food %>% 
  mutate(grupo = kmean_fit$cluster) %>% 
  arrange(grupo) %>% 
  select(Country, grupo)

pc <- prcomp(food[, -1], scale. = TRUE)
pc

# Proporção da variância explicada (2 dimensões)
sum(pc$sdev[1:2])/sum(pc$sdev)

tibble(
  pais = food$Country,
  PC1 = pc$x[,1],
  PC2 = pc$x[,2],
  grupo = as.factor(kmean_fit$cluster)
) %>% 
  ggplot(
    aes(x = PC1, y = PC2, label = pais, color = grupo)
  ) +
  geom_text()
```



```{r}
# Proporção da variância explicada (2 dimensões)
sum(pc$sdev[1:3])/sum(pc$sdev)

library(plotly)

tibble(
  pais = food$Country,
  PC1 = pc$x[,1],
  PC2 = pc$x[,2],
  PC3 = pc$x[,3],
  grupo = as.factor(kmean_fit$cluster)
) %>% 
plot_ly(
  x = ~PC1, 
  y = ~PC2, 
  z = ~PC3, 
  type = "scatter3d",
  mode = "text",
  color = ~grupo,
  text = ~pais
)
```

```{r}
library(leaflet)

paises <- read_csv("coord.csv")

df <- tibble(
  pais = as.character(food$Country),
  grupo = as.factor(kmean_fit$cluster)
) %>%
  mutate(
    pais = case_when(
      pais == "Czechoslovakia" ~ "Czech Republic",
      pais == "W Germany" ~ "Germany",
      pais == "UK" ~ "United Kingdom",
      pais == "Yugoslavia" ~ "Serbia",
      pais == "USSR" ~ "Russia",
      TRUE ~ pais
    )
  ) %>% 
  filter(pais != "E Germany") %>%
  mutate(
    color = case_when(
      grupo == 1 ~ "red",
      grupo == 2 ~ "green",
      grupo == 3 ~ "blue"
    )
  ) %>% 
  left_join(paises, by = "pais")

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'white',
  library = 'ion',
  markerColor = df$color
)

leaflet(df) %>% 
  addTiles() %>% 
  addAwesomeMarkers(
    lng = ~long, 
    lat = ~lat, 
    popup = ~pais,
    icon = icons 
  )
```



```{r}
df_face <- read_csv("rede_social.csv")


rec_face <- recipe(df_face) %>%
  step_modeimpute(all_nominal()) %>% 
  step_meanimpute(all_numeric()) %>% 
  step_dummy(all_nominal(), one_hot = TRUE) %>% 
  step_center(all_numeric()) %>%
  step_scale(all_numeric()) %>% 
  step_rm(age, gradyear)
rec_face

prep_face <- prep(rec_face, training = df_face,verbose = TRUE)

face <- bake(prep_face, newdata = df_face)
```

```{r}
set.seed(42)
clusters <- 4
kmean_fit <- kmeans(face, clusters)

kmean_fit$centers %>%
  as.tibble() %>%
  mutate(grupo = 1:clusters) %>% 
  gather(variable, center, -grupo) %>%
  mutate(
    posneg = ifelse(center < 0, "neg", "pos"),
    center = abs(center)
  ) %>%
  group_by(grupo) %>% 
  top_n(5, center) %>% 
  ggplot(aes(x = variable, y = center, fill = posneg)) +
  geom_bar(stat = "identity") +
  facet_wrap(~grupo, nrow = 2, scales = "free")
  
```

