---
title: "case-arvores"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pacotes 

```{r}
library(recipes)
library(caret)
library(dplyr)
library(rsample)
```

# Banco de dados

```{r}
data(attrition, package = "rsample")
glimpse(attrition)
```

# Ajustando modelos

## Preparação da base

```{r}
receita <- recipe(Attrition ~ ., data = attrition) %>%
  step_dummy(all_nominal(), - all_outcomes(), one_hot = TRUE)
```

## Esquema de validação

```{r}
metricas <- function(data, lev = NULL, model = NULL) {
  c(
    defaultSummary(data, lev, model), 
    twoClassSummary(data, lev, model)
  )
}

train_control <- trainControl(
  method = "cv", 
  number = 5, 
  classProbs = TRUE,
  summaryFunction = metricas
)
```

## Árvores de decisão

```{r}
modelo <- train(
  receita,
  data = attrition,
  method = "rpart", 
  trControl = train_control
)
modelo


plot(modelo$finalModel, compress = TRUE)
text(modelo$finalModel, use.n = TRUE)

library(rpart.plot)
rpart.plot(modelo$finalModel)

library(rattle)
fancyRpartPlot(modelo$finalModel)
```

### Modificando o tuning grid

```{r}
tuning_grid <- data.frame(cp = seq(0.005, 0.02, length.out = 25))
modelo <- train(
  receita,
  data = attrition,
  method = "rpart", 
  trControl = train_control, 
  tuneGrid = tuning_grid
)
modelo
```

## Random Forests

```{r}
modelo <- train(
  receita,
  data = attrition,
  method = "ranger", 
  trControl = train_control
)
modelo
```

### Modificando o tuning grid

```{r}
tuning_grid <- expand.grid(
  splitrule = "extratrees",
  mtry = c(35, 55, 65, 73),
  min.node.size = c(1, 15, 30)
)

modelo <- train(
  receita,
  data = attrition,
  method = "ranger", 
  trControl = train_control,
  tuneGrid = tuning_grid
)
modelo
```

# Exercício

Ajuste um Random Forest p/ a base de Crédito. Será que conseguimos um resultado melhor?
Identifique as variáveis importantes.

```{r}
data(credit_data, package = "recipes")
glimpse(credit_data)
```



