---
title: "case-mba"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pacotes

```{r}
library(readr)
```


# Banco de dados

```{r}
mba <- read_csv("data_mba.csv")
```

# Modelos

## Arules

```{r}
library(arules)
library(dplyr)

x <- mba %>%
  select(-DT) %>%
  group_by(ID_CUPOM) %>%
  mutate(
    PRODUTO = PRODUTO %>% 
      stringr::str_extract("[^ ]* [^ ]*") %>%
      stringr::str_replace_all("[:space:]{1,}", "_")
  ) %>%
  summarise(PRODUTO = list(PRODUTO))

names(x$PRODUTO) <- x$ID_CUPOM
x <- as(x$PRODUTO, "transactions")

x
summary(x)
```

```{r}
modelo <- apriori(x, parameter = list(support = 0.2, confidence = 0.9), 
                  appearance = list (default="lhs",rhs="IOG_ACTIVIA")
                  )

inspect(modelo)

library(arulesViz)
plot(
  modelo, 
  method="graph", 
  control=list(type="items"), 
  shading = "lift"
  )

plot(modelo, method = "grouped")
```

# Próximos passos:

- http://dsnotes.com/post/2017-06-28-matrix-factorization-for-recommender-systems-part-2/
- pacote recommenderlab

