---
title: "case-classificacao"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pacotes

```{r}
library(recipes)
library(caret)
library(dplyr)
library(rsample)
```

# Banco de dados

```{r}
data("credit_data")
glimpse(credit_data)
```

```{r}
ggplot(credit_data, aes(x = Status)) + geom_bar()
p <- GGally::ggduo(
  credit_data,
  columnsY = "Status", 
  columnsX = colnames(credit_data)[colnames(credit_data) != "Status"]
  )
p
```

# Ajustando modelos

## Preparação

```{r}
metricas <- function(data, lev = NULL, model = NULL) {
  c(
    defaultSummary(data, lev, model), 
    twoClassSummary(data, lev, model)
  )
}

train_control <- trainControl(
  method = "cv", 
  number = 5, 
  classProbs = TRUE,
  summaryFunction = metricas
)
```

## Regressão Logística

```{r}
receita <- recipe(Status ~ ., data = credit_data) %>%
  step_meanimpute(all_numeric(), -all_outcomes()) %>%
  step_modeimpute(all_nominal(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_corr(all_predictors()) %>%
  step_nzv(all_predictors())

receita

modelo <- train(
  receita, 
  credit_data, 
  method = "glm", 
  family = "binomial", 
  trControl = train_control
)

modelo
summary(modelo)
cor(credit_data %>% select_if(is.numeric), use = "complete.obs")
```

## LASSO

```{r}
receita <- recipe(Status ~ ., data = credit_data) %>%
  step_meanimpute(all_numeric(), -all_outcomes()) %>%
  step_modeimpute(all_nominal(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors())

receita

modelo <- train(
  receita, 
  train_data, 
  method = "glmnet", 
  family = "binomial", 
  trControl = train_control, 
  metric = "ROC"
)

modelo
modelo$bestTune
coef(modelo$finalModel, s = modelo$bestTune$lambda)

tune_grid <- expand.grid(alpha = c(0, 0.55, 1), lambda = 10^(-6:0))
modelo <- train(
  receita, 
  train_data, 
  method = "glmnet", 
  family = "binomial", 
  trControl = train_control, 
  metric = "ROC", 
  tuneGrid = tune_grid
)

modelo
modelo$bestTune
coef(modelo$finalModel, s = modelo$bestTune$lambda)
plot(modelo)
varImp(modelo)
```

# Exercício

Ajuste um modelo de regressão logística e um de LASSO p/ prever o churn de funcionários no banco de dados `attrtion`.

```{r}
data(attrition, package = "rsample")
glimpse(attrition)
```

```{r}
# Criar a receita

# Ajustar o modelo

# Modificar os tuning-parameters

# Verificar quais são as variáveis mais importantes

```









    
    