---
title: "case-forecast"
output: html_document
---

# Pacotes

```{r}
library(forecast)
library(dplyr)
library(tidyr)
library(ggplot2)
```

# Base

```{r}
elecdaily <- readr::read_csv("elecdaily.csv")
```

# Gráficos

Visão geral das séries

```{r}
elecdaily %>%
  gather(Serie, valor, -Date) %>%
  ggplot(aes(x = Date, y = valor, color = Serie)) + 
  geom_line() + 
  facet_grid(Serie ~ ., scales = "free_y")
```

Relação da demanda com a temperatura e com dias de trabalho.

```{r}
elecdaily %>%
  ggplot(aes(x = Temperature, y = Demand, color = as.factor(WorkDay))) + 
  geom_point()
```

# Separar 1 semana para previsão

```{r}
elecdaily_train <- elecdaily[1:(365 - 7), ]
elecdaily_test <- elecdaily[(365 - 7 + 1):365, ]
```

# Modelo de regressão

```{r}
library(caret)
library(recipes)

train_control <- trainControl(
  method = "timeslice", 
  initialWindow = 240, 
  horizon = 7
)

receita <- recipe(Demand ~ ., data = elecdaily_train) %>%
  step_rm(Date) %>%
  step_poly(Temperature, options = list(degree = 2, raw = TRUE)) %>%
  step_lag(Demand, lag = c(1:4))

modelo <- train(
  receita, 
  elecdaily_train,
  method = "lm",
  trControl = train_control
)

modelo
```

Previsão para outra base

```{r}
predito_caret <- predict(modelo, rbind(elecdaily_train, elecdaily_test))
RMSE_caret <- sqrt(mean((tail(predito_caret, 7) - elecdaily_test$Demand)^2))
RMSE_caret
```

# Usando o forecast

```{r}
xreg <- cbind(MaxTemp = elecdaily_train[, "Temperature"],
              MaxTempSq = elecdaily_train[, "Temperature"]^2,
              Workday = elecdaily_train[, "WorkDay"])
fit <- auto.arima(elecdaily_train[, "Demand"], xreg = xreg)
checkresiduals(fit)
```

Fazendo previsões

```{r}
xreg <- cbind(MaxTemp = elecdaily_test[, "Temperature"],
              MaxTempSq = elecdaily_test[, "Temperature"]^2,
              Workday = elecdaily_test[, "WorkDay"])

fcast <- forecast(fit, xreg = xreg)
autoplot(fcast) + ylab("Electicity demand (GW)")
predito_forecast <- fcast$mean %>% as.numeric()
RMSE_forecast <- sqrt(mean((predito_forecast - elecdaily_test$Demand)^2))
RMSE_forecast
```


# Referência

- https://otexts.org/fpp2/lagged-predictors.html